<?php

namespace biz\sitewebBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * motifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class motifRepository extends EntityRepository
{
}
